#include<bits/stdc++.h>
using namespace std;

// Ty le quy doi
const double DOLLARS_PER_POINT = 10.0; // 10 do = 1 diem

// Lop Vi
class Wallet {
public:
    int walletId;
    int balance;
    vector<string> transactionLog;

    Wallet() : walletId(-1), balance(0) {}
    Wallet(int id, int initialBalance = 0) : walletId(id), balance(initialBalance) {}
};

// Lop Nguoi dung
class User {
public:
    string username;
    string passwordHash;
    string fullName;
    string email;
    int walletId;
    bool isManager;
    bool isAutoGenerated;
    
    User() : username(""), passwordHash(""), fullName(""), email(""), walletId(-1), 
             isManager(false), isAutoGenerated(false) {}
        
    User(string uname, string pwd, string name, string mail, int wId, bool manager = false)
        : username(uname), passwordHash(pwd), fullName(name), email(mail), walletId(wId),
          isManager(manager), isAutoGenerated(false) {}
};
    
// Danh sach nguoi dung va vi
unordered_map<string, User> users;
unordered_map<int, Wallet> wallets;

// Ham bam mat khau (gia lap voi salt don gian)
string hashPassword(string password) {
    hash<string> hasher;
    string salt = "simpleSalt123";
    return to_string(hasher(password + salt));
}

// Sinh mat khau ngau nhien
string sinhMatKhauNgauNhien() {
    string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    string pwd;
    srand(time(0));
    for (int i = 0; i < 8; i++) {
        pwd += chars[rand() % chars.size()];
    }
    return pwd;
}

// Sinh OTP
string sinhOTP() {
    srand(time(0));
    string otp = "";
    for (int i = 0; i < 6; i++) {
        otp += to_string(rand() % 10);
    }
    return otp;
}
